### ISSUE TITLE
Changing network type stops the stream and it never resumes again

### ISSUE THREAD

**Issue by WildS0ft** [Poniverse/Ponyville-Live-Mobile#2]
Playback doesn't resume when switching network type from mobile to WiFi and vice versa. The stream stops with a long pause, it then plays for 1-2 seconds and then permanently stops.

Not a showstopper, but a nuisance when walking in our out of WiFi coverage or the mobile data temporarily loses connection when you are out and about =)

**Comment by thomcuddihy** [comment]
Hmm.. Good catch. This is an issue with the media player element handling the stream closing. Will add code to retry connection a sensible number of times before abort. Can reuse code in native.

**Comment by thomcuddihy** [comment]
Mediaplayer component doesn't trip onError on stream dropout, and onInfo listener doesn't reliably inform of stream loss/reset. Had to implement a pretty hacky workaround for this version (Ionic/Cordova), that can't (rather, shouldn't) be reused in native. Will use a network connection manager to handle changes in connectivity, and send appropriate messages to static service for handling instead. 
Cheers WildS0ft, expect an update in your honour in the next few hours ~tinker

**Comment by WildS0ft** [comment]
Good work /) Glad I could be of some service =) Looking forward to the release of the native app as well.

/WildSoft

**Comment by thomcuddihy** [comment]
Cheers WildSoft. Your namesake edition is live at https://play.google.com/store/apps/details?id=com.ponyvillelive.pvlmobile
Feel free to send any more issues our way!
Looking forward to native release too - let me know if you would like to join closed alpha.
(\ tinker

**Comment by WildS0ft** [comment]
@thomcuddihy awesome :blush: thus far I've only had time to test it a little, glad to be rid of the strobe light and it does reconnect when switching networks now :smiley: However it does take some time for it to react (35 seconds of silence on switch).
**When manually switching network mode:**
After the stream stops it's silent for 28 seconds, it then plays a 2 second leftover chunk followed by another 5 seconds of silence until it continues to stream. 

Not sure if anything can be done about it, but I'd rather you continue your work on the native app instead :wink: 

Sure, I'd be willing to help report bugs on the native release as well.
