### ISSUE TITLE
Device LED notification is rapidly blinking red

### ISSUE THREAD

**Issue by WildS0ft** [Poniverse/Ponyville-Live-Mobile#3]
The device notification LED is rapidly blinking red when running the app and the screen is turned off. It never stops unless it gets interrupted by another notification, but starts right back up again when a new song comes on.

**Device:** Sony Z1 Compact (D5503)
**Android:** 5.1.1

**Comment by thomcuddihy** [comment]
This is the default action of the de.appplant.cordova.plugin package used to display system notifications, but, agreed, it's a terrible design choice. Have disabled manually in package source. Will be resolved in next build release.
