### ISSUE TITLE
Audio is not paused when disconnecting external audio source (e.g. headset)

### ISSUE THREAD

**Issue by WildS0ft** [Poniverse/Ponyville-Live-Mobile#4]
Audio is not paused/stopped when disconnecting an external audio source, e.g. a headset or a bluetooth device.

**Comment by thomcuddihy** [comment]
This relies on capturing those events, and they are not implemented in Ionic/Cordova. The native app project does capture these (along with AudioBecomingNoisy). This issue will be addressed in upcoming release of native app.
